version: '2'
services:
  postgres:
    container_name: clair_postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair_clair
    restart: always
    image: quay.io/coreos/clair
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - /var/tmp:/config
    command: [-config, /config/config.yaml]

networks:
  default:
    external:
      name: ${CUSTOM_NETWORK_NAME}
